apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: '{{ .Values.env }}-argo'
spec:
  generators:
    - git:
      repoURL: '{{ .Values.repo }}'
      revision: '{{ .Values.ref }}'
      directories:
        - path: charts/apps/*
          include: '.*'
          exclude: '.*.disabled'
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: default
      source:
        repoURL: '{{ .Values.repo }}'
        targetRevision: '{{ .Values.ref }}'
        path: charts/apps/{{`{{path.basename}}`}}
        helm:
          values: |
            globals: {{ .Values.globals | toYaml | nindent 14 }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .Values.globals.env }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
