name: homelab
services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - $PWD/.data/local/postgres:/var/lib/postgresql/data
