apiVersion: v1
kind: Namespace
metadata:
  name: homelab

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: homelab
spec:
  interval: 60m
  url: https://github.com/morten-olsen/homelab-operator
  ref:
    branch: main

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
  namespace: homelab
spec:
  releaseName: operator
  interval: 60m
  chart:
    spec:
      chart: charts/operator
      sourceRef:
        kind: GitRepository
        name: homelab
        namespace: homelab