apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: homelab-operator

build:
  cluster: {}
  artifacts:
    - image: homelaboperator
      context: .
      docker:
        dockerfile: Dockerfile

manifests:
  helm:
    releases:
      - name: homelab-operator
        chartPath: charts/operator
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_homelaboperator}}'
          image.tag: '{{.IMAGE_TAG_homelaboperator}}'

deploy:
  # Use kubectl to apply the manifests.
  kubectl: {}
