apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: homelab-operator

build:
  artifacts:
    - image: zot.olsen.cloud/homelaboperator
      context: ./images/operator
      docker:
        dockerfile: Dockerfile

manifests:
  helm:
    releases:
      - name: homelab-operator
        chartPath: charts/operator
        namespace: homelab
        setValueTemplates:
          image.repository: "zot.local/homelaboperator"
          image.tag: "{{.IMAGE_TAG_zot_olsen_cloud_homelaboperator}}"

deploy:
  # Use kubectl to apply the manifests.
  kubectl: {}
