apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvshows
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-tvshows
  nfs:
    path: '{{ .Values.tvshows.path }}'
    server: '{{ .Values.host }}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvshows
spec:
  storageClassName: manual-tvshows
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
