apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-data'
spec:
  storageClassName: '{{ .Values.environment }}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
