apiVersion: homelab.mortenolsen.pro/v1
kind: OidcClient
metadata:
  name: test-client
spec:
  environment: dev
  redirectUris:
    - url: https://localhost:3000/api/v1/authentik/oauth2/callback
      matchingMode: strict
