apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: homelab-operator-local-path

---

apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: default
spec:
  containers:
    - name: example-container
      image: alpine
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: example-volume
          mountPath: /data
      resources:
        limits:
          memory: 100Mi
          cpu: "0.1"
        requests:
          memory: 50Mi
          cpu: "0.05"
  volumes:
    - name: example-volume
      persistentVolumeClaim:
        claimName: example-pvc