apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath: null
  nfs:
    path: '{{ .Values.movies.path }}'
    server: '{{ .Values.host }}'
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
