apiVersion: v1
kind: PersistentVolume
metadata:
  name: podcasts
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-podcasts
  nfs:
    path: '{{ .Values.podcasts.path }}'
    server: '{{ .Values.host }}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcasts
spec:
  storageClassName: manual-podcasts
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
