/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface K8SDomainEndpointV1 {
  spec?: {
    destination: {
      name: string;
      namespace?: string;
      port: {
        number: number;
      };
    };
    domain: string;
    subdomain: string;
  };
  status?: {
    conditions: {
      lastTransitionTime: string;
      message?: string;
      reason?: string;
      status: "True" | "False" | "Unknown";
      type: string;
    }[];
    observedGeneration: number;
  };
}
