/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface K8SETCDSnapshotFileV1 {
  spec?: {
    location?: string;
    metadata?: {
      [k: string]: string;
    };
    nodeName?: string;
    s3?: {
      bucket?: string;
      endpoint?: string;
      endpointCA?: string;
      insecure?: boolean;
      prefix?: string;
      region?: string;
      skipSSLVerify?: boolean;
    };
    snapshotName?: string;
  };
  status?: {
    creationTime?: string;
    error?: {
      message?: string;
      time?: string;
    };
    readyToUse?: boolean;
    size?: string;
  };
}
