/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface K8SHelmChartV1 {
  spec?: {
    authPassCredentials?: boolean;
    authSecret?: {
      name?: string;
    };
    backOffLimit?: number;
    bootstrap?: boolean;
    chart?: string;
    chartContent?: string;
    createNamespace?: boolean;
    dockerRegistrySecret?: {
      name?: string;
    };
    failurePolicy?: string;
    helmVersion?: string;
    insecureSkipTLSVerify?: boolean;
    jobImage?: string;
    plainHTTP?: boolean;
    podSecurityContext?: {
      appArmorProfile?: {
        localhostProfile?: string;
        type?: string;
      };
      fsGroup?: number;
      fsGroupChangePolicy?: string;
      runAsGroup?: number;
      runAsNonRoot?: boolean;
      runAsUser?: number;
      seLinuxOptions?: {
        level?: string;
        role?: string;
        type?: string;
        user?: string;
      };
      seccompProfile?: {
        localhostProfile?: string;
        type?: string;
      };
      supplementalGroups?: number[];
      supplementalGroupsPolicy?: string;
      sysctls?: {
        name?: string;
        value?: string;
      }[];
      windowsOptions?: {
        gmsaCredentialSpec?: string;
        gmsaCredentialSpecName?: string;
        hostProcess?: boolean;
        runAsUserName?: string;
      };
    };
    repo?: string;
    repoCA?: string;
    repoCAConfigMap?: {
      name?: string;
    };
    securityContext?: {
      allowPrivilegeEscalation?: boolean;
      appArmorProfile?: {
        localhostProfile?: string;
        type?: string;
      };
      capabilities?: {
        add?: string[];
        drop?: string[];
      };
      privileged?: boolean;
      procMount?: string;
      readOnlyRootFilesystem?: boolean;
      runAsGroup?: number;
      runAsNonRoot?: boolean;
      runAsUser?: number;
      seLinuxOptions?: {
        level?: string;
        role?: string;
        type?: string;
        user?: string;
      };
      seccompProfile?: {
        localhostProfile?: string;
        type?: string;
      };
      windowsOptions?: {
        gmsaCredentialSpec?: string;
        gmsaCredentialSpecName?: string;
        hostProcess?: boolean;
        runAsUserName?: string;
      };
    };
    set?: {
      [k: string]: {
        [k: string]: unknown;
      };
    };
    targetNamespace?: string;
    timeout?: string;
    valuesContent?: string;
    version?: string;
  };
  status?: {
    conditions?: {
      message?: string;
      reason?: string;
      status?: string;
      type?: string;
    }[];
    jobName?: string;
  };
}
