/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface K8SSecretRequestV1 {
  spec?: {
    data: {
      chars?: string;
      encoding?: "utf-8" | "base64" | "base64url" | "hex";
      key: string;
      length?: number;
      value?: string;
    }[];
    secretName?: string;
  };
  status?: {
    conditions: {
      lastTransitionTime: string;
      message?: string;
      reason?: string;
      status: "True" | "False" | "Unknown";
      type: string;
    }[];
    observedGeneration: number;
  };
}
