apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: "{{ .Release.Name }}-prometheus-community"
spec:
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: "{{ .Release.Name }}-prometheus-community"
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        name: "{{ .Release.Name }}-prometheus-community"
        namespace: "{{ .Release.Namespace }}"
  interval: 1h
  values:
    grafana:
      env:
        GF_SERVER_ROOT_URL: https://grafana.olsen.cloud # TODO

---
apiVersion: homelab.mortenolsen.pro/v1
kind: HttpService
metadata:
  name: "{{ .Release.Name }}-prometheus-community"
spec:
  environment: "{{ .Values.globals.environment }}"
  subdomain: "{{ .Values.grafana.subdomain }}"
  destination:
    host: "{{ .Release.Name }}-prometheus-community-grafana.{{ .Release.Namespace }}.svc.cluster.local"
    port:
      number: 80

---
apiVersion: homelab.mortenolsen.pro/v1
kind: OidcClient
metadata:
  name: "{{ .Release.Name }}-grafana"
spec:
  environment: "{{ .Values.globals.environment }}"
  redirectUris:
    - path: /login/generic_oauth
      subdomain: "{{ .Values.grafana.subdomain }}"
      matchingMode: strict
