apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: '{{ .Release.Name }}-kyverno'
spec:
  interval: 1h
  url: https://kyverno.github.io/kyverno/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: '{{ .Release.Name }}-kyverno'
spec:
  chart:
    spec:
      chart: kyverno
      reconcileStrategy: ChartVersion
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        name: '{{ .Release.Name }}-kyverno'
        namespace: '{{ .Release.Namespace }}'
  interval: 1h
  values: {}
