globals:
  environment: prod
  domain: olsen.cloud
  timezone: Europe/Amsterdam
image:
  repository: lscr.io/linuxserver/calibre-web
  tag: latest@sha256:f4159edfe9bbf1b07389d249b241004f6e15360f5d3cc01029f5865632b613cd
  pullPolicy: IfNotPresent
subdomain: calibre-web
