globals:
  environment: prod
image:
  repository: headscale/headscale
  tag: latest@sha256:ea9b5ee06274d757a4d52103de56cd11a9c393acb19d9a35f4b9fe52ada410de
  pullPolicy: IfNotPresent
subdomain: headscale
