globals:
  environment: prod
  timezone: Europe/Amsterdam
  domain: olsen.cloud
image:
  repository: docker.n8n.io/n8nio/n8n
  tag: latest@sha256:746f90a251005a1bdbe2b7ebbce7d14eba6eb634739d157e4f9778d61f07dae3
  pullPolicy: IfNotPresent
subdomain: n8n
