apiVersion: v1
kind: PersistentVolume
metadata:
  name: music
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-music
  nfs:
    path: '{{ .Values.music.path }}'
    server: '{{ .Values.host }}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
spec:
  storageClassName: manual-music
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
