apiVersion: v1
kind: PersistentVolume
metadata:
  name: pictures
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-pictures
  nfs:
    path: '{{ .Values.pictures.path }}'
    server: '{{ .Values.host }}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pictures
spec:
  storageClassName: manual-pictures
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
