apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}'
  labels:
    app: '{{ .Release.Name }}'
spec:
  type: LoadBalancer # Set to NodePort/ClusterIP if you prefer
  ports:
    - name: http
      port: 11434
      targetPort: http
      protocol: TCP
  selector:
    app: '{{ .Release.Name }}'
