globals:
  environment: prod
image:
  repository: ghcr.io/open-webui/open-webui
  tag: main@sha256:05aaa81eb4094038a16f0ae056342e3515d1912a30e41b828bfd3731fbe36a6c
  pullPolicy: IfNotPresent
subdomain: openwebui
