apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: '{{ .Release.Name }}'
spec:
  interval: 1h
  url: https://helm.goharbor.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: '{{ .Release.Name }}'
spec:
  chart:
    spec:
      chart: harbor
      reconcileStrategy: ChartVersion
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        name: '{{ .Release.Name }}'
        namespace: '{{ .Release.Namespace }}'
  interval: 1h
  values:
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: '{{ .Values.globals.environment }}'
        jobservice:
          jobLog:
            storageClass: '{{ .Values.globals.environment }}'
        database:
          storageClass: '{{ .Values.globals.environment }}'
        redis:
          storageClass: '{{ .Values.globals.environment }}'
        trivy:
          storageClass: '{{ .Values.globals.environment }}'
