apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  labels:
    app: "{{ .Release.Name }}"
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    listener 1883 0.0.0.0
    allow_anonymous true
